# Generated by Django 3.2.6 on 2021-08-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('urls', models.URLField()),
                ('created_datetime', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created_datetime',),
            },
        ),
    ]
